### ISSUE TITLE
Item Search Method

### ISSUE THREAD

**Issue by bengrisz** [AppWrenchStudios/NearBuy#47]
Return list of items where name, category, or brand match the "string" entered in search.

Should return to endpoint: /api/items

Maybe:
/api/items?search="string"

**Comment by nigelg11861** [comment]
Here is a mock apiary end point to model the JSON request and response.  The URL can change but I think this is approximately correct.  As an additional sidenote I think POST is appropriate because GET doesn't allow one to send JSON in the request body (in addition to the points we discussed in groupme)

http://docs.nearbuyitemsearch.apiary.io/#

**Comment by bengrisz** [comment]
Had to install Java Runtime Environment for Solr

sudo apt-get update
sudo apt-get install default-jre


To start using Sunspot and Solr (after 'sunspot_rails' and 'sunspot_solr' gems are added to Gemfile)

bundle
rails generate sunspot_rails:install
rake sunspot:solr:start
